Feature/75246 ui export to excel
equinor/procosys-js-frontend pull request #228
Opened 2020-08-24 12:36 UTC by arildbjerkenes

Currently we get a CORS policy issue when we try to generate with 10000+ tags. It works when we have a small list. Please let me know if there is better way to handle the response object.

2020-08-24 14:48 UTC, Cnordbo requested changes
When it comes to the CORS error, this is a server issue. Usually its a 500 error that isnt handled properly. Verify with API.

2020-08-24 14:48 UTC, Cnordbo commented on src/modules/Preservation/http/PreservationApiClient.ts
> + * Get preserved tags for currently logged in user in current plant context
Wrong description

2020-08-24 14:48 UTC, Cnordbo commented on src/modules/Preservation/views/ScopeOverview/ScopeOverview.tsx
> +                    tempLink.click();
tempLink needs to be removed from the DOM after clicking it.

2020-08-24 14:48 UTC, Cnordbo commented on src/modules/Preservation/views/ScopeOverview/ScopeOverview.tsx
> +                    const tempLink = document.createElement('a');
There should be a `display: none` attribute on this, so that it doesnt "bump" the dom when added.

2020-08-24 17:12 UTC, arildbjerkenes commented on src/modules/Preservation/http/PreservationApiClient.ts
> + * Get preserved tags for currently logged in user in current plant context
Fixed.

2020-08-24 17:13 UTC, arildbjerkenes commented on src/modules/Preservation/views/ScopeOverview/ScopeOverview.tsx
> +                    tempLink.click();
Yepp

2020-08-24 18:28 UTC, arildbjerkenes commented on src/modules/Preservation/views/ScopeOverview/ScopeOverview.tsx
> +                    tempLink.click();
fixed

2020-08-24 18:28 UTC, arildbjerkenes commented on src/modules/Preservation/views/ScopeOverview/ScopeOverview.tsx
> +                    const tempLink = document.createElement('a');
fixed

2020-08-24 18:28 UTC, arildbjerkenes commented on src/modules/Preservation/http/PreservationApiClient.ts
> + * Get preserved tags for currently logged in user in current plant context
fixed

2020-08-25 10:45 UTC, Cnordbo approved these changes

2020-08-25 13:05 UTC, merged