CPO general info page and context
equinor/procosys-js-frontend pull request #237
Opened 2020-08-31 07:56 UTC by bratli

Call for punch out general info page. Assume if we come from main the project ID and commpkg ID are in the url as params.

2020-08-31 07:58 UTC, janhagevold commented
test

2020-08-31 14:33 UTC, Cnordbo requested changes

2020-08-31 14:33 UTC, Cnordbo commented on src/modules/CallForPunchOut/index.tsx
> +const Preservation = (): JSX.Element => {
Rename module export

2020-08-31 14:33 UTC, Cnordbo commented on src/modules/CallForPunchOut/views/AddCPO/AddCPO.tsx
> +    const [endTime, setEndTime] = useState<string | null>();
Move to single object set in state, as this will avoid having a ton of properties set here.

2020-08-31 14:33 UTC, Cnordbo commented on src/modules/CallForPunchOut/context/CallForPunchOutContext.tsx
> +    },[]);
Can be removed

2020-08-31 14:33 UTC, Cnordbo commented on src/modules/CallForPunchOut/views/AddCPO/GeneralInfo/GeneralInfo.tsx
> +    endTime?: string | null;
Adjust to match changes mentioned in `AddCPO`

2020-09-01 14:24 UTC, Cnordbo requested changes
I would suggest that all state handling for the form values are kept inside the GeneralInfo component. Along with the "Next" button logic. This makes sure that only "GeneralInfo" knows when its OK to move to the next step, and the logic can be contained to that module, without involving the parent "AddCPO" in that regards. 

When all logic passes, the next button is activated. 
When next button is pressed. `props.setGeneralInfo` is called on with the new object.

2020-09-01 14:24 UTC, Cnordbo commented on src/modules/CallForPunchOut/views/AddCPO/AddCPO.tsx
> +                return copy;
Use spread operator `return { ...gi, projectId: projectId }`

2020-09-01 14:24 UTC, Cnordbo commented on src/modules/CallForPunchOut/views/AddCPO/GeneralInfo/GeneralInfo.tsx
> +                setGeneralInfo(copy);
Use spread operator `{ ..generalInfo, poType: poType}`

2020-09-01 14:24 UTC, Cnordbo commented on src/modules/CallForPunchOut/views/AddCPO/GeneralInfo/GeneralInfo.tsx
> +            copy.poType = newPoType;
use spread operator

2020-09-01 14:24 UTC, Cnordbo commented on src/modules/CallForPunchOut/views/AddCPO/GeneralInfo/GeneralInfo.tsx
> +        copy.projectId = filteredProjects[index].id;
use spread operator

2020-09-01 14:24 UTC, Cnordbo commented on src/modules/CallForPunchOut/views/AddCPO/GeneralInfo/GeneralInfo.tsx
> +                    copy.title = e.target.value;
use spread operator

2020-09-01 14:24 UTC, Cnordbo commented on src/modules/CallForPunchOut/views/AddCPO/GeneralInfo/GeneralInfo.tsx
> +                    copy.description = e.target.value;
use spread operator

2020-09-01 14:24 UTC, Cnordbo commented on src/modules/CallForPunchOut/views/AddCPO/GeneralInfo/GeneralInfo.tsx
> +                        copy.startDate = e.target.value;
use spread operator

2020-09-01 14:24 UTC, Cnordbo commented on src/modules/CallForPunchOut/views/AddCPO/GeneralInfo/GeneralInfo.tsx
> +                        copy.startTime = e.target.value;
use spread operator

2020-09-01 14:24 UTC, Cnordbo commented on src/modules/CallForPunchOut/views/AddCPO/GeneralInfo/GeneralInfo.tsx
> +                        copy.endDate = e.target.value;
use spread operator

2020-09-01 14:24 UTC, Cnordbo commented on src/modules/CallForPunchOut/views/AddCPO/GeneralInfo/GeneralInfo.tsx
> +                        copy.endTime = e.target.value;
use spread operator

2020-09-01 14:24 UTC, Cnordbo commented on src/modules/CallForPunchOut/views/AddCPO/GeneralInfo/GeneralInfo.tsx
> +                        copy.location = e.target.value;
use spread operator

2020-09-01 14:24 UTC, Cnordbo commented on src/modules/CallForPunchOut/views/AddCPO/GeneralInfo/GeneralInfo.tsx
> +                    onChange={(e: React.ChangeEvent<HTMLInputElement>): void => {
separate logical event handling outside of the return statement

2020-09-01 14:24 UTC, Cnordbo commented on src/modules/CallForPunchOut/views/AddCPO/GeneralInfo/GeneralInfo.tsx
> +                    onChange={(e: React.ChangeEvent<HTMLInputElement>): void => {
separate logical event handling outside of the return statement

2020-09-01 14:24 UTC, Cnordbo commented on src/modules/CallForPunchOut/views/AddCPO/GeneralInfo/GeneralInfo.tsx
> +                    onChange={(e: React.ChangeEvent<HTMLInputElement>): void => {
separate logical event handling outside of the return statement

2020-09-01 14:24 UTC, Cnordbo commented on src/modules/CallForPunchOut/views/AddCPO/GeneralInfo/GeneralInfo.tsx
> +                    onChange={(e: React.ChangeEvent<HTMLInputElement>): void => {
separate logical event handling outside of the return statement

2020-09-01 14:24 UTC, Cnordbo commented on src/modules/CallForPunchOut/views/AddCPO/GeneralInfo/GeneralInfo.tsx
> +                    onChange={(e: React.ChangeEvent<HTMLInputElement>): void => {
separate logical event handling outside of the return statement

2020-09-01 14:24 UTC, Cnordbo commented on src/modules/CallForPunchOut/views/AddCPO/GeneralInfo/GeneralInfo.tsx
> +                onChange={(e: React.ChangeEvent<HTMLInputElement>): void => {
separate logical event handling outside of the return statement

2020-09-01 14:24 UTC, Cnordbo commented on src/modules/CallForPunchOut/views/AddCPO/GeneralInfo/GeneralInfo.tsx
> +                onChange={(e: React.ChangeEvent<HTMLInputElement>): void => {
separate logical event handling outside of the return statement

2020-09-01 14:24 UTC, Cnordbo commented on src/modules/CallForPunchOut/views/AddCPO/GeneralInfo/GeneralInfo.tsx
> +                const copy = Object.assign({}, generalInfo);
when using current state to update the same state, its recommended to do it directly from `setState`

```js
setGeneralInfo(current => ({...current, poType})
```

Should be updated on all occurrences.

2020-09-02 06:52 UTC, bratli commented on src/modules/CallForPunchOut/views/AddCPO/GeneralInfo/GeneralInfo.tsx
> +                onChange={(e: React.ChangeEvent<HTMLInputElement>): void => {
Is this resolved with spread ?

2020-09-02 06:53 UTC, bratli commented on src/modules/CallForPunchOut/views/AddCPO/GeneralInfo/GeneralInfo.tsx
> +                const copy = Object.assign({}, generalInfo);
Need som input from you in person.... Gives me error if I do setGeneralInfo(current => ({...current, poType}) in GeneralInfo, so instead I am doing setGeneralInfo({...current, poType}). Is this ok?

2020-09-02 07:28 UTC, bratli commented on src/modules/CallForPunchOut/views/AddCPO/GeneralInfo/GeneralInfo.tsx
> +                onChange={(e: React.ChangeEvent<HTMLInputElement>): void => {
Will have it here as long as it is only one line

2020-09-02 07:31 UTC, bratli commented
> I would suggest that all state handling for the form values are kept inside the GeneralInfo component. Along with the "Next" button logic. This makes sure that only "GeneralInfo" knows when its OK to move to the next step, and the logic can be contained to that module, without involving the parent "AddCPO" in that regards.
> 
> When all logic passes, the next button is activated.
> When next button is pressed. `props.setGeneralInfo` is called on with the new object.

For now I will not make any changes here. Agree with the concept, and will do a re-evaluation when more of the components are implemented. Main concern is that if all steps are 'valid' for creating IPO, and we are at a step, we can click 'Create' from the step, and last changes will not be included as they are only stored in child component, not parent.

2020-09-02 07:43 UTC, Cnordbo approved these changes
Looks good, look at the feedback and OK to merge when done.

2020-09-02 07:43 UTC, Cnordbo commented on src/modules/CallForPunchOut/views/AddCPO/GeneralInfo/GeneralInfo.tsx
> +            }
looks like you can use your own function `setPoTypeForm` here.

2020-09-02 07:43 UTC, Cnordbo commented on src/modules/CallForPunchOut/views/AddCPO/GeneralInfo/GeneralInfo.tsx
> +    let requestCanceler: Canceler;
this must be moved to inside the `useEffect`

2020-09-02 08:15 UTC, merged