Warning when project is closed
equinor/procosys-js-frontend pull request #260
Opened 2020-09-07 11:14 UTC by arildbjerkenes

2020-09-07 11:42 UTC, kfaln requested changes

2020-09-07 11:42 UTC, kfaln commented on src/modules/Preservation/index.tsx
> +            <ClosedProjectWarning />
No check to see whether the project is **actually** closed? Seems like this is always rendered regardless of project status...

2020-09-08 08:43 UTC, arildbjerkenes commented on src/modules/Preservation/index.tsx
> +            <ClosedProjectWarning />
I was not finished with this. That's why I didn't put anyone as reviewer.

2020-09-11 06:29 UTC, bratli commented on src/http/ProCoSysClient.ts
> +    async getProjectAsync(projectId: number, setRequestCanceller?: RequestCanceler): Promise<SingleProjectResponse> {
why cant we just use the Projects/{projectName} endpoint in preservation API?

2020-09-11 08:07 UTC, arildbjerkenes commented on src/http/ProCoSysClient.ts
> +    async getProjectAsync(projectId: number, setRequestCanceller?: RequestCanceler): Promise<SingleProjectResponse> {
The preservation database only contains projects where tags are added to scope.

2020-09-11 08:08 UTC, arildbjerkenes commented
I have simplified the solution, to avoid complications.

2020-09-11 13:54 UTC, Cnordbo requested changes
A lot cleaner solution, good job. 

Just a few issues, and we are good to go :)

2020-09-11 13:54 UTC, Cnordbo commented on src/modules/Preservation/ClosedProjectWarning.tsx
> +        let requestCancellor: Canceler | null = null;
missing return statement in useEffect to cancel the request

2020-09-11 13:54 UTC, Cnordbo commented on src/modules/Preservation/ClosedProjectWarning.tsx
> +    const warningIcon = <EdsIcon name='warning_outlined' color={tokens.colors.interactive.warning__resting.rgba} size={24} />;
inline in return statement

2020-09-11 13:54 UTC, Cnordbo commented on src/modules/Preservation/ClosedProjectWarning.tsx
> +                {warningIcon} <IconSpacer /> Selected project {project.name} is closed.
Avoid using spacing components, as this will wrap differently on smaller screens. Rather wrap the text in a component that applies margins.

2020-09-11 13:54 UTC, Cnordbo commented on src/modules/Preservation/style.ts
> +`;
i think your missing a merge from master. This is removed.

2020-09-14 06:54 UTC, arildbjerkenes commented on src/modules/Preservation/ClosedProjectWarning.tsx
> +        let requestCancellor: Canceler | null = null;
fixed

2020-09-14 06:57 UTC, arildbjerkenes commented on src/modules/Preservation/ClosedProjectWarning.tsx
> +    const warningIcon = <EdsIcon name='warning_outlined' color={tokens.colors.interactive.warning__resting.rgba} size={24} />;
Hm, ok.

2020-09-14 07:13 UTC, merged

2020-09-14 07:13 UTC, Cnordbo approved these changes