77632: select DP and MDP scope when coming from 'New'
equinor/procosys-js-frontend pull request #266
Opened 2020-09-09 14:27 UTC by bratli

2020-09-10 08:24 UTC, Cnordbo commented
Input overflows selected scope component

![image](https://user-images.githubusercontent.com/385693/92700977-bef64d00-f34f-11ea-8758-9d84dd2b708d.png)

2020-09-10 08:25 UTC, Cnordbo commented
Scrollbar is introduced even if content doesnt go past the bottom 

![image](https://user-images.githubusercontent.com/385693/92701146-ec42fb00-f34f-11ea-9602-44cfd157252e.png)

2020-09-10 08:25 UTC, Cnordbo commented
Missing tests

2020-09-10 08:30 UTC, Cnordbo commented
Removing selected scopes doesnt work
![image](https://user-images.githubusercontent.com/385693/92701690-96228780-f350-11ea-8775-d522ba19017b.png)

![image](https://user-images.githubusercontent.com/385693/92701719-9f135900-f350-11ea-94f8-a7f1765cb46b.png)

2020-09-10 08:31 UTC, Cnordbo requested changes
See conversation comments

2020-09-10 08:31 UTC, Cnordbo commented on src/modules/CallForPunchOut/views/AddCPO/SelectScope/SelectScope.style.ts
> +`;
use container borders instead of this divider. 

See perservation on how its done there on ScopeOverview and the Filter component.

2020-09-10 08:31 UTC, Cnordbo commented on src/modules/CallForPunchOut/views/AddCPO/SelectScope/CommPkgTable.tsx
> +            const copy = [...selectedCommPkgScope.slice(0, selectedIndex), ...selectedCommPkgScope.slice(selectedIndex + 1)];
be explicit about naming variables.

2020-09-10 14:54 UTC, bratli commented on src/modules/CallForPunchOut/views/AddCPO/SelectScope/CommPkgTable.tsx
> +            const copy = [...selectedCommPkgScope.slice(0, selectedIndex), ...selectedCommPkgScope.slice(selectedIndex + 1)];
are you referring to copy or selectedIndex as being implicit?

2020-09-11 14:00 UTC, Cnordbo commented on src/modules/CallForPunchOut/views/AddCPO/SelectScope/CommPkgTable.tsx
> +            const copy = [...selectedCommPkgScope.slice(0, selectedIndex), ...selectedCommPkgScope.slice(selectedIndex + 1)];
copy, just be specific about what the variable is, or what its about to contain. 

in the lines of : 

// i like this notation better, as it represents what it actually is, rather then what its a copy of as this no longer is a copy when its edited. 
`newSelectedCommPkgScope` 
`updatedListOfSelectedCommPkgScope`

2020-09-14 07:59 UTC, Cnordbo requested changes

2020-09-14 07:59 UTC, Cnordbo commented on src/modules/CallForPunchOut/views/AddCPO/SelectScope/__tests__/SelectScope.test.jsx
> +
We should add a test that verified that the selectedMcPkgScope function updates correctly

2020-09-14 07:59 UTC, Cnordbo commented on src/modules/CallForPunchOut/views/AddCPO/SelectScope/__tests__/McPkgTable.test.jsx
> +    //TODO: add more tests
If you know what tests to add use `test.todo('Name of test')` as this is easier for you then the next person looking at this.

2020-09-14 07:59 UTC, Cnordbo commented on src/modules/CallForPunchOut/views/AddCPO/SelectScope/__tests__/CommPkgTable.test.jsx
> +    //TODO: add more tests
If you know what tests to add use `test.todo('Name of test')` as this is easier for you then the next person looking at this.

2020-09-14 07:59 UTC, Cnordbo commented on src/modules/CallForPunchOut/views/AddCPO/SelectScope/Table.style.ts
> +        }
isnt this hidden when using disableRipple=true?

2020-09-14 07:59 UTC, Cnordbo commented on src/modules/CallForPunchOut/views/AddCPO/SelectScope/Table.style.ts
> +    }
This overwrites the EDS design?

2020-09-14 07:59 UTC, Cnordbo commented on src/modules/CallForPunchOut/views/AddCPO/SelectScope/SelectScope.style.ts
> +    width: 70%;
could also use `flex: 2` and `flex: 1` on the adjacent component to say "Take up 2 parts of the available space" and "take up 1 part of the available space", which basically is what flexbox is designed for.

2020-09-14 11:22 UTC, bratli commented on src/modules/CallForPunchOut/views/AddCPO/SelectScope/Table.style.ts
> +        }
Not for the checkbox in the header

2020-09-14 11:23 UTC, bratli commented on src/modules/CallForPunchOut/views/AddCPO/SelectScope/Table.style.ts
> +    }
This is for the checkboxes in the table. Without this they become small and blurry.

2020-09-14 11:27 UTC, bratli commented on src/modules/CallForPunchOut/views/AddCPO/SelectScope/__tests__/SelectScope.test.jsx
> +
I am waiting to add some tests here for when the endpoints are ready, as I think I will have to rewrite some code anyways, and dont want to do the tests twice

2020-09-14 11:28 UTC, bratli commented on src/modules/CallForPunchOut/views/AddCPO/SelectScope/McPkgTable.tsx
> +];
Dont have an API client, will have to revisit all tests once this is in place.

2020-09-14 11:28 UTC, bratli commented on src/modules/CallForPunchOut/views/AddCPO/SelectScope/CommPkgTable.tsx
> +];
Dont have an API client, will have to revisit all tests once this is in place.

2020-09-17 12:44 UTC, Cnordbo approved these changes
A few formalities and your good to go. Well done!

2020-09-17 12:44 UTC, Cnordbo commented on src/modules/InvitationForPunchOut/style.ts
>      }
Remove

2020-09-17 12:44 UTC, Cnordbo commented on src/modules/InvitationForPunchOut/views/CreateIPO/SelectScope/__tests__/SelectScope.test.jsx
> +    it('Renders with disabled next button when not empty scope', async () => {
should this be `enabled next button` ?

2020-09-17 14:14 UTC, bratli commented on src/modules/InvitationForPunchOut/views/CreateIPO/SelectScope/__tests__/SelectScope.test.jsx
> +    it('Renders with disabled next button when not empty scope', async () => {
good catch

2020-09-17 14:26 UTC, merged