Add error boundary component
equinor/procosys-js-frontend pull request #274
Opened 2020-09-14 11:59 UTC by Cnordbo

This adds a component that will prevent your other components or modules from crashing the entire application if an error occures. 

Usage: 
```js
<ErrorBoundary message="Optional custom error message" >
    <SuccessfullComponent />
</ErrorBoundary>
```

Important: 
Its always the mounting component that has to add the ErrorBoundary to the application. Not the component that the error is emerging from. 

So this does not work as a wrapper for every component, but rather as a wrapper that is added at the usage point. 

In the example above, that means that <SuccessFullComponent> can not have "its own protection" by just wrapping its return statement with <ErrorBoundary>

Example - will not work: 
```js
const myFaultFunction = () => throw 'error'

const SuccessfullComponent = () => {
    return (<ErrorBoundary><p>{myFaultyFunction()}</p></ErrorBoundary>
}
```

2020-09-15 11:08 UTC, kfaln requested changes

2020-09-15 11:08 UTC, kfaln commented on src/components/ErrorBoundary/__tests__/ErrorBoundary.test.jsx
> +    it('Renders error with custom error message', () => {
Duplicate (and faulty) description with the one above.

2020-09-15 11:08 UTC, kfaln commented on src/components/ErrorBoundary/index.tsx
> +        console.error('CRITICAL ERROR OCCURED');
A bit dramatic? It might not be that critical :) "Unexpected" or "Unhandled" maybe?

2020-09-15 11:08 UTC, kfaln commented on src/components/ErrorBoundary/index.tsx
> +                    <Typography variant="h1">{!this.props.message ? 'Sorry, an unexpected error occured' : this.props.message}</Typography>
Not sure how often we will provide the custom error message. So perhaps we should refine the default message a bit? Perhaps this is the place we put info like "please contact support if the problem persists bla bla"...

2020-09-16 08:03 UTC, Cnordbo commented on src/components/ErrorBoundary/index.tsx
> +        console.error('CRITICAL ERROR OCCURED');
Its think this only handles the most critical cases, as its an exception that will break the component and prevent it from rendering (which causes this to catch it). 

I think this is only caught if the component itself throws an exception, and not if a general promise is not caught.

2020-09-16 08:04 UTC, Cnordbo commented on src/components/ErrorBoundary/index.tsx
> +                    <Typography variant="h1">{!this.props.message ? 'Sorry, an unexpected error occured' : this.props.message}</Typography>
Good idea.

2020-09-16 09:19 UTC, kfaln approved these changes

2020-09-16 14:47 UTC, merged