First version of ProCoSysSettings to handle all settings
equinor/procosys-js-frontend pull request #275
Opened 2020-09-15 11:49 UTC by paal123

First version of ProCoSysSettings, currently only replacing the direct read of settings.json

Preparing for feature flags, but no implementation yet.

2020-09-15 14:03 UTC, Cnordbo requested changes
A few minor details, can be merged when considered or fixed.

2020-09-15 14:03 UTC, Cnordbo commented on src/auth/AuthService.tsx
> +const defaultLoginScopes = JSON.parse(ProCoSysSettings.auth.defaultScopes.replace(/'/g, '"'));
Add this parsing directly to `ProCoSysSettings` static property, so thats its ready to use.

2020-09-16 05:45 UTC, paal123 commented on src/auth/AuthService.tsx
> +const defaultLoginScopes = JSON.parse(ProCoSysSettings.auth.defaultScopes.replace(/'/g, '"'));
Agree!

2020-09-16 05:45 UTC, paal123 commented on settings.template.json
> +    },
Agree!

2020-09-16 06:00 UTC, merged