Add force update on click for preservation requirements
equinor/procosys-js-frontend pull request #306
Opened 2020-10-07 10:10 UTC by janhagevold

2020-10-09 11:11 UTC, Cnordbo commented
This issue is not just related to the preservation requirement, so the change should affect all library items. 

Remember to also check other options for forcing an update on the component. As toggling a variable true/false will/can cause a double render which is not needed. 

(useReducer, increment state by 1 e.e)

It could also be that we should see if there is a way to just change the active tree element to the newly created one, or just render back to the default view after creating the new entity, instead of showing the newly created entity within the same view.

2020-10-09 11:40 UTC, Cnordbo requested changes
This issue is not just related to the preservation requirement, so the change should affect all library items.

Remember to also check other options for forcing an update on the component. As toggling a variable true/false will/can cause a double render which is not needed.

(useReducer, increment state by 1 e.e)

It could also be that we should see if there is a way to just change the active tree element to the newly created one, or just render back to the default view after creating the new entity, instead of showing the newly created entity within the same view.

2020-10-13 07:58 UTC, arildbjerkenes commented on src/modules/PlantConfig/views/Library/LibraryTreeview/LibraryTreeview.tsx
> +            props.forceUpdate();
I think we should make it possible to use force update even if there is a library item.

2020-10-13 08:01 UTC, arildbjerkenes approved these changes

2020-10-13 10:11 UTC, janhagevold commented on src/modules/PlantConfig/views/Library/LibraryTreeview/LibraryTreeview.tsx
> +            props.forceUpdate();
At the moment, this will only re-render the component with no side effects. An idea would be that a forced re-render resets the component state, i.e. after editing to discard changes made without saving.

2020-10-13 10:28 UTC, Cnordbo commented on src/modules/PlantConfig/views/Library/Library.tsx
> +                forceUpdate={forceUpdate}
is this needed? 
if state changes in this component, doesnt that just re-render all childs without having this referenced passed down?

2020-10-15 04:33 UTC, merged