77708: attachment view in wizard
equinor/procosys-js-frontend pull request #307
Opened 2020-10-08 14:16 UTC by bratli

-Can upload file by clicking button
-Can drag and drop files

2020-10-08 14:17 UTC, bratli commented on src/modules/InvitationForPunchOut/views/CreateIPO/Attachments/Attachments.tsx
> +        const newAttachmentsList = [...attachments.splice(index, 1)]; //todo: this is not necessary, but without anything here delete is not working
@Cnordbo

2020-10-09 11:36 UTC, Cnordbo requested changes

2020-10-09 11:36 UTC, Cnordbo commented on src/modules/InvitationForPunchOut/views/CreateIPO/Attachments/Attachments.tsx
> +        setAttachments([...attachments].concat(files));
concat returns a new array, so the spread operator here is probably not needed. 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat

2020-10-09 11:36 UTC, Cnordbo commented on src/modules/InvitationForPunchOut/views/CreateIPO/Attachments/Attachments.tsx
> +        const files = [...event.dataTransfer.files];
You can use `event.dataTransfer.files` directly within concat.

2020-10-09 11:36 UTC, Cnordbo commented on src/modules/InvitationForPunchOut/views/CreateIPO/Summary/Summary.tsx
> +    const getAttachments = (attachment: File, index: number): JSX.Element => {
method naming, `getAttachments` - it just sounds like your getting the actual attachments, not just a single component. 

As well as pluralization of the name, when it only handles a single entity. 

This can also be created per render by just running
```js
const attachmentList = attachments.map((attachment, index) => (
<Row key={index}>
                <Cell>{attachment.name}</Cell>
            </Row>
));
```

And then render out the table based on the length of this directly. 

```js
{ attachmentList.length > 0 && <TableSection......> {attachmentList} </> }
```

2020-10-09 11:36 UTC, Cnordbo commented on src/modules/InvitationForPunchOut/views/CreateIPO/Attachments/Attachments.tsx
> +    setAttachments: React.Dispatch<React.SetStateAction<File[]>>;
Instead of manipulating the state directly. What about creating methods that handle this at the parent level. 

`onAttachmentAdded`
`onAttachmentRemoved`

or just `onChange`

this way only the parent has control of what is actually is passed back down to the child element. and state is only mutated in a single place. Reducing the side effects of this component.

2020-10-09 11:47 UTC, bratli commented on src/modules/InvitationForPunchOut/views/CreateIPO/Attachments/Attachments.tsx
> +    setAttachments: React.Dispatch<React.SetStateAction<File[]>>;
Would we send the Files to the parent component?

Also, do you think this is how it should be done in all components? I think we would end up with a lot of logic in the parent

2020-10-09 11:56 UTC, bratli commented on src/modules/InvitationForPunchOut/views/CreateIPO/Attachments/Attachments.tsx
> +    setAttachments: React.Dispatch<React.SetStateAction<File[]>>;
Check it out if the last commit is what you meant :) I think this is nice!

2020-10-09 12:12 UTC, Cnordbo commented on src/modules/InvitationForPunchOut/views/CreateIPO/Attachments/Attachments.tsx
> +    setAttachments: React.Dispatch<React.SetStateAction<File[]>>;
Yes, the list of Files would be sent to the parent, if we used the `onChange`. 
Otherwise, in the case of `onAttachmentAdded/removed` you would just send the element that is requested to be removed, or the element that is requested to be added. 

In any case the the parent would be responsible for updating the attachments state value based on that information.

In general, we should think of components as "self contained" meaning, that they only "possibly" alter states of parents or siblings based on events that happen in that component, and that the parent is responsible for reacting upon those events. 
Then the parent is responsible for submitting new data to the child which should be displayed. 
And only where it makes sense (like i believe it does here, since attachments doesnt really do any logic back and forth with the server, its just a tool for the parent component)

If this component would have had all the logic related to attachments within it (communicating with the server), I would not suggest the same approach as i am suggesting here. Altough this approach could be wrapped within another component that handles the server logic as well. 

ex. (with som fluff for illustration)

```js
<IHandleServerUploading>
   const {attachments, setAttachments} = useState<Attachment>([]);

   const upload = () => {
       //... Upload logic
   }

   const onAttachmentAdded = (newAttachment: Attachment) => setAttachments((existingAttachments) => 
   [...existingAttachments, newAttachment];

   const onAttachmentRemoved= (index: number) => setAttachments((existingAttachments) => {
     const newAttachmentList = [...existingAttachments];
     newAttachmentList.splice(index,1);
     return newAttachmentList;
   }

   <IHandleFileSelection_and_dragNDrop 
   allowedFileTypes={['jpg']} 
   dragAndDrop={false} 
   fileIcons={true} 
   attachments={attachments} 
   onAttachmentAdded={onAttachmentAdded}
   onAttachmentRemoved={onAttachmentRemoved}
    />

<button type="submit" onClick={upload} />
</IHandleServerUploading>
```

This has the following benefits: 
* We reduce the state mutation happening in child components of parent components (reducing side-effects)
* We can easily re-use the component later
* We are reducing the responsibility of the attachments component, or add more support to it later based on filetypes e.e

Hope this makes sense.

2020-10-09 12:15 UTC, Cnordbo commented on src/modules/InvitationForPunchOut/views/CreateIPO/Attachments/Attachments.tsx
> +    setAttachments: React.Dispatch<React.SetStateAction<File[]>>;
with the onChange way of doing it, this would basically work the same, but then we pass back a copy of the attachments list, with the new file, or with the old file removed (a complete list) - and then the parent could either just set that directly as its own attachments value, or choose to validate before updating the list. (for instance in case of deleting an already uploaded file)

2020-10-09 12:32 UTC, Cnordbo approved these changes
Have a look at the latest comments, PR can be merged after that. Good work!

2020-10-09 12:32 UTC, Cnordbo commented on src/modules/InvitationForPunchOut/views/CreateIPO/Summary/Summary.tsx
> +            { attachments.length > 0 &&
You can use attachmentList here as well :)

2020-10-09 12:32 UTC, Cnordbo commented on src/modules/InvitationForPunchOut/views/CreateIPO/CreateIPO.tsx
> +        const attachmentsCopy = [...attachments];
when manipulating state where we depend on the current value of the state, its best to use the callback function that can be sent with the setter. 

```js
setAttachments((currentState) => ....)
```

2020-10-09 12:32 UTC, Cnordbo commented on src/modules/InvitationForPunchOut/views/CreateIPO/CreateIPO.tsx
> +        const attachmentsCopy = [...attachments];
This gives us a guarantee that the `attachment` state is actual current state when its being executed.

2020-10-09 12:32 UTC, Cnordbo commented on src/modules/InvitationForPunchOut/views/CreateIPO/CreateIPO.tsx
> +        const attachmentsCopy = [...attachments];
https://reactjs.org/docs/state-and-lifecycle.html#state-updates-may-be-asynchronous

2020-10-09 12:32 UTC, Cnordbo commented on src/modules/InvitationForPunchOut/views/CreateIPO/CreateIPO.tsx
> +        setAttachments(attachments.concat(files));
Same as previous comment regarding use of current state value.

2020-10-12 06:45 UTC, merged