Feature 78028:   UI General info tab
equinor/procosys-js-frontend pull request #317
Opened 2020-10-26 06:26 UTC by janhagevold

2020-10-26 08:32 UTC, bratli requested changes

2020-10-26 08:32 UTC, bratli commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/index.tsx
> +            <ParticipantsTable participants={participantList} completePunchOut={completePunchOut} />
Is it possible to make the table horizontally scrollable if it cannot fit on the screen, or is this difficult when working with widths? From what I see this is not a big issue (and I think I recall this being tricky), so dont spend too much time on it.

2020-10-26 08:32 UTC, bratli commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/ParticipantsTable/index.tsx
> +                        <Cell as="th" scope="col" style={{verticalAlign: 'middle'}}>Note/Comment</Cell>
Just being picky, but I think we should decide on either note or comment. You can ask Jon. If he said to have it like this then it is fine

2020-10-26 08:32 UTC, bratli commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/ParticipantsTable/index.tsx
> +                            <Cell as="td" style={{verticalAlign: 'middle', minWidth: '160px'}}>
Just a note - I have asked Jon as well - but I think the attended and note properties should be disabled until the user clicks "Complete punch out", then he will get a popup (https://statoildeveloper.visualstudio.com/Statoil.NextGenProCoSys/_backlogs/backlog/Statoil.NextGenProCoSys%20Team/Features/?workitem=77740) where he will do this, and then complete. We will leave it like this for now.

2020-10-26 08:32 UTC, bratli commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/ParticipantsTable/index.tsx
> +        // TODO: Determine participant permission for current user
More detail in another comment, but I think signed will be "-" for everyone except maybe first two participants. Then we will have getCompleted and getAccepted instead, which will probably be properties on the invitation.

2020-10-26 08:32 UTC, bratli commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/ParticipantsTable/index.tsx
> +    const handleCompletePunchOut = async (index: number): Promise<any> => {
We will probably change this a bit as well (to show popup). 
As mentioned in pevious comments, I dont think we will set signedAt/By, but complete the punchout, and get new response from endpoint where completedAt/By is set.

2020-10-26 08:32 UTC, bratli commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/ParticipantsTable/CustomCells.tsx
> +import { Typography } from '@material-ui/core';
Use Typography from EDS

2020-10-26 08:32 UTC, bratli commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/ParticipantsTable/CustomCells.tsx
> +            <CustomSwitch checked={status} onChange={(): void => onChange(!status)}/>
Check if EDS has a swith we can use 
https://eds-storybook-react-development.azurewebsites.net/?path=/story/components-selection-controls-switch--switch-control

2020-10-26 08:32 UTC, bratli commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/ParticipantsTable/CustomFields.tsx
> +import { Switch, TextField, Tooltip, withStyles } from '@material-ui/core';
EDS has text field and Switch.
The Tooltip in EDS is buggy, so keep using the one from material-ui :-)

2020-10-26 11:12 UTC, janhagevold commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/ParticipantsTable/index.tsx
> +                        <Cell as="th" scope="col" style={{verticalAlign: 'middle'}}>Note/Comment</Cell>
Column renamed Notes

2020-10-26 11:22 UTC, janhagevold commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/ParticipantsTable/index.tsx
> +        // TODO: Determine participant permission for current user
To be determined in another task

2020-10-26 11:22 UTC, janhagevold commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/ParticipantsTable/index.tsx
> +    const handleCompletePunchOut = async (index: number): Promise<any> => {
Adjusted in popup task

2020-10-27 05:34 UTC, janhagevold commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/ParticipantsTable/CustomFields.tsx
> +import { Switch, TextField, Tooltip, withStyles } from '@material-ui/core';
done

2020-10-27 05:35 UTC, janhagevold commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/ParticipantsTable/CustomCells.tsx
> +            <CustomSwitch checked={status} onChange={(): void => onChange(!status)}/>
done

2020-10-27 05:35 UTC, janhagevold commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/ParticipantsTable/CustomCells.tsx
> +import { Typography } from '@material-ui/core';
done

2020-10-27 05:35 UTC, janhagevold commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/index.tsx
> +import { Typography } from '@material-ui/core';
done

2020-10-27 05:35 UTC, janhagevold commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/index.tsx
> +                    <Typography variant="caption">Meeting point</Typography>
location used

2020-10-27 05:35 UTC, janhagevold commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/index.tsx
> +                <Typography variant="h6">General generalInfo</Typography>
fixed

2020-10-27 05:36 UTC, janhagevold commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/types.d.ts
> +    id?: string;
done

2020-10-27 05:36 UTC, janhagevold commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/types.d.ts
> +    invitationSent: boolean;
removed invitation

2020-10-27 05:36 UTC, janhagevold commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/types.d.ts
> +    meetingPoint: string;
location used

2020-10-27 05:37 UTC, janhagevold commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/types.d.ts
> +    signedBy?: string;
CompetedAt, CompletedBy, AcceptedBy, AcceptedAt columns added to Invitation (GeneralInfoType)

2020-10-27 05:37 UTC, janhagevold commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/dummyData.ts
> +            signedBy: undefined,
done

2020-10-27 06:56 UTC, bratli commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/types.d.ts
> +    id?: string;
We can fix this when getting data from endpoint (unless you have something else to fix), but id here is a int.

2020-10-27 07:04 UTC, bratli approved these changes
See comments

2020-10-27 07:04 UTC, bratli commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/index.tsx
> +import { CompletedType, Participant } from './types';
This in not used - will it be?

2020-10-27 07:04 UTC, bratli commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/types.d.ts
> +export type CompletedType = {
Not used, will it be?

2020-10-27 07:04 UTC, bratli commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/ParticipantsTable/CustomCells.tsx
> +import { Typography } from '@equinor/eds-core-react';
move in with top import from EDS

2020-10-27 07:13 UTC, bratli requested changes

2020-10-27 07:13 UTC, bratli commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/ParticipantsTable/index.tsx
> -                                {participant.signedAt ? `${getFormatDate(participant.signedAt)} ${getFormatTime(participant.signedAt)}` : '-'}
I think we still need signet at column in table btw!

2020-10-28 07:59 UTC, bratli approved these changes

2020-10-28 10:06 UTC, merged