Reschedule dialog for scope list
equinor/procosys-js-frontend pull request #319
Opened 2020-10-27 15:58 UTC by arildbjerkenes

Because the dialog contains input fields, it was not possible to utilize the Dialog component in a good way.

2020-10-27 22:01 UTC, Cnordbo requested changes

2020-10-28 07:17 UTC, arildbjerkenes commented on src/modules/Preservation/views/ScopeOverview/ScopeOverview.tsx
> +import React, { useEffect, useRef, useState, useCallback } from 'react';
Fixed

2020-10-28 07:55 UTC, arildbjerkenes commented on src/modules/Preservation/views/ScopeOverview/RescheduleDialog.tsx
> +const RescheduleDialog = (props: RescheduleDialogProps): JSX.Element => {
Looks nicer. Thanks.

2020-10-28 14:03 UTC, arildbjerkenes commented on src/modules/Preservation/views/ScopeOverview/RescheduleDialog.tsx
> +const RescheduleDialog = (props: RescheduleDialogProps): JSX.Element => {
Added

2020-10-28 14:11 UTC, Cnordbo approved these changes

2020-10-28 14:30 UTC, merged