Feature/79294 support for mobile device
equinor/procosys-js-frontend pull request #343
Opened 2020-11-09 07:49 UTC by arildbjerkenes

# Description

Please include a summary of the change and which issue is fixed. 
List any external dependencies that are required for this change.

Completes: DevOps#FILL_IN_YOUR_ISSUE_ID

# Checklist:

- [ ] I have performed a self-review of my own code.
- [ ] I have linked my DevOps task and the PR (both on GitHub and DevOps).
- [ ] My code is easy to read, and comments are added where needed.
- [ ] My code is covered by tests.

2020-11-09 09:11 UTC, arildbjerkenes commented
I will have Jon to confirm the design, but code is ready for review.

2020-11-19 09:46 UTC, arildbjerkenes commented
NOTE: The new tests added here is currently not working.

2020-11-26 14:54 UTC, Cnordbo requested changes

2020-11-27 10:31 UTC, arildbjerkenes commented on src/modules/Preservation/views/ScopeOverview/ScopeOverview.style.ts
> +    }
Klarer vi å importere styling.ts til variables.scss?

2020-11-27 11:32 UTC, Cnordbo commented on src/modules/Preservation/views/ScopeOverview/ScopeOverview.style.ts
> +    }
Nei, dessverre. 
Vi kan kjøre andre veien, at vi lager en rot komponent med styled components som tar setter variablene, i stedet for variables.scss. Da kan man også inkludere styling.ts der. 
Men det kan godt opprettes en tech sak på det i stedet for å ta det inn her nå, så for nå så blir media queryene kopiert 2 plasser tenker jeg.

2020-11-27 11:33 UTC, Cnordbo commented on src/modules/Preservation/views/ScopeOverview/ScopeOverview.style.ts
> +    }
Med mindre du vil gjøre refaktoreringen :)

2020-11-29 17:28 UTC, arildbjerkenes commented on src/modules/Preservation/views/ScopeOverview/ScopeOverview.style.ts
> +    }
Har allerede kopiert :-)

2020-11-30 06:53 UTC, arildbjerkenes commented on src/modules/Preservation/views/ScopeOverview/ScopeOverview.tsx
> +                    <HeaderPartOne showActions={showActions}>
I tried both first-child and first-of-type, but of some reason, the whole header for included. I renamed it to LeftPartOfHeader. It should be understandable.

2020-11-30 11:48 UTC, Cnordbo requested changes

2020-11-30 11:48 UTC, Cnordbo commented on src/modules/Header/style.ts
> +        display: flex;
not all display properties is `flex`, use it only if you know what your trying to do. 
Try setting this to `unset` so that it inherits its natural display settings.

2020-11-30 11:48 UTC, Cnordbo commented on src/modules/Header/style.ts
> +    display:flex;
not all display properties is `flex`, use it only if you know what your trying to do. 
I think this can be removed from here.

2020-11-30 11:48 UTC, Cnordbo commented on src/modules/Header/style.ts
> +    width: 100%;
nav is 100% width by default. remove flex styling from surrounding element to fix width issues. (separate comments)

2020-11-30 11:48 UTC, Cnordbo commented on src/modules/Preservation/views/ScopeOverview/ScopeOverview.style.ts
> +    width:100%;
flex is designed to take up all available space. if used properly. 
setting the width property on flex elements is rarely needed. 
use `flex: 1` instead.

Have a look here: 
https://codepen.io/Cnordbo/pen/zYKGYBz

2020-11-30 11:48 UTC, Cnordbo commented on src/modules/Preservation/views/ScopeOverview/ScopeOverview.style.ts
> +            display:flex;
`display: unset`

2020-11-30 11:48 UTC, Cnordbo commented on src/modules/Preservation/views/ScopeOverview/ScopeTable.style.ts
> +export const Container = styled.div<any>`
Why is `any` added here?

2020-11-30 11:48 UTC, Cnordbo commented on src/modules/Preservation/views/ScopeOverview/ScopeTable.style.ts
> +            display:table-cell;
try using `unset` to get the natural display property.

2020-11-30 11:48 UTC, Cnordbo commented on src/modules/Preservation/views/ScopeOverview/ScopeTable.tsx
> +                }
Switch out with default params: 

```tsx
this.props.setRefreshScopeListCallback((maxHeight: number, refreshOnResize = false) => {
  if (this.refObject.current) {
       this.refObject.current.props.options.maxBodyHeight = maxHeight;
       this.refreshOnResize = refreshOnResize;
       this.refObject.current.onSearchChangeDebounce();
   }
  });
```

2020-11-30 11:48 UTC, Cnordbo commented on src/modules/Preservation/views/ScopeOverview/__tests__/ScopeOverview.test.jsx
> +    });
no need to use `await act()...` or the `await waitFor(..)`

```jsx
it('Should display description column', async () => {

        const history = createMemoryHistory();
        const { getByText } = render(
            <Router history={history}>
                <ScopeOverview />
            </Router>
        );          
        expect(getByText('Description')).toBeInTheDocument();
    });
```

2020-12-01 10:37 UTC, arildbjerkenes commented on src/components/Flyout/style.ts
> +    overflow-x: scroll;
Ok, other changes have made this unnecessary.

2020-12-01 10:48 UTC, arildbjerkenes commented on src/core/services/ModalDialogService/style.ts
> +    }
My thinking was that on a mobile the width will be so small anyway, that using 95vw makes sense. No need to complicate this. If we see another need at some point, we can change things then. Also, later we might start using an EDS component.

2020-12-01 10:54 UTC, arildbjerkenes commented on src/modules/Header/index.tsx
> +                <ShowOnMobile>
If you display procosys on a small device, open the menu, and then change the screen size to desktop size, then showMobileMenu will still be true. If you change to small again, the menu shows.

2020-12-01 10:55 UTC, arildbjerkenes commented on src/modules/Header/style.ts
> +        display: flex;
Ah, unset. That's what I was trying to do :-).

2020-12-01 11:48 UTC, arildbjerkenes commented on src/modules/Preservation/views/ScopeOverview/ScopeOverview.style.ts
> +    width:100%;
I got issues with this. I don't want to experiment more with this for now.

2020-12-01 11:50 UTC, arildbjerkenes commented on src/modules/Preservation/views/ScopeOverview/ScopeTable.style.ts
> +export const Container = styled.div<any>`
forgot to remove.

2020-12-01 11:59 UTC, arildbjerkenes commented on src/modules/Preservation/views/ScopeOverview/ScopeTable.tsx
> +                }
Nice!

2020-12-01 13:39 UTC, arildbjerkenes commented on src/modules/Preservation/views/ScopeOverview/ScopeTable.style.ts
> +            display:table-cell;
No, did not work.

2020-12-01 13:50 UTC, merged