Feature 78700:  UI warning when leaving page unsaved
equinor/procosys-js-frontend pull request #358
Opened 2020-11-26 13:37 UTC by janhagevold

# Description

- Add dirty context for CreateIPO
- Add dirty context for ViewIPO

Completes: AB#78700

# Checklist:

- [ ] I have performed a self-review of my own code.
- [ ] I have linked my DevOps task using the AB# tag.
- [ ] My code is easy to read, and comments are added where needed.
- [ ] My code is covered by tests.

2020-11-26 14:51 UTC, Cnordbo requested changes

2020-11-26 14:51 UTC, Cnordbo commented on src/modules/InvitationForPunchOut/views/ViewIPO/index.tsx
> +        clearDirtyState();
We might want to avoid usage of `clearDirtyState`. This clears all dirty state, and could possibly cause unwanted sideeffects further down the road. 
I think this API is mainly used when pressing "confirm" on the alert that shows up. which would clear all dirtystate.

2020-11-26 14:51 UTC, Cnordbo commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/ParticipantsTable/index.tsx
> +    const { setDirtyStateFor, isDirty, unsetDirtyStateFor } = useDirtyContext();
I believe you can test this by reading out the isDirty values in your tests. Verifying that your protecting and triggering the dirty state on the appropriate inputs or actions.

2020-12-10 13:53 UTC, Cnordbo commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/ParticipantsTable/__tests__/ParticipantsTable.test.jsx
> +configure({ testIdAttribute: 'id' });
why override this instead of using the actual testid attribute ?

2020-12-10 13:53 UTC, Cnordbo commented on src/modules/InvitationForPunchOut/views/ViewIPO/utils.ts
> +
I really hate that these types are put into `utils`. 
They seem to deserver their own file, just called enums.ts or something

2020-12-11 08:32 UTC, janhagevold commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/ParticipantsTable/__tests__/ParticipantsTable.test.jsx
> +configure({ testIdAttribute: 'id' });
Eds Switch component does not take attribute data-testid. The configure was  scoped for the file for consistency throughout the tests.

2020-12-11 08:33 UTC, janhagevold commented on src/modules/InvitationForPunchOut/views/ViewIPO/utils.ts
> +
Enums moved to separate enums.ts files

2020-12-14 09:44 UTC, bratli approved these changes

2020-12-14 10:07 UTC, merged