Edit IPO
equinor/procosys-js-frontend pull request #386
Opened 2020-12-17 12:30 UTC by arildbjerkenes

# Description

Edit of IPO

Completes: AB#77809

# Checklist:

- [ ] I have performed a self-review of my own code.
- [ ] I have linked my DevOps task using the AB# tag.
- [ ] My code is easy to read, and comments are added where needed.
- [ ] My code is covered by tests.

2020-12-17 12:31 UTC, arildbjerkenes commented
Note: I will merge with master and implement support for external email.

2020-12-18 08:37 UTC, bratli requested changes

2020-12-18 08:37 UTC, bratli commented on src/modules/InvitationForPunchOut/views/ViewIPO/ViewIPOHeader.tsx
> +                    <Link to={`/EditIPO/${props.ipoId}`}>
Edit-knapp bør være disabled hvis en IPO er completed, accepted, eller cancelled

2020-12-18 08:37 UTC, bratli commented on src/modules/InvitationForPunchOut/views/CreateIPO/CreateIPOHeader.tsx
>                      <Button variant='outlined'>Cancel</Button>
legg på logikk på cancel-button hvis vi er i edit-mote

2020-12-18 10:35 UTC, bratli requested changes

2020-12-18 10:35 UTC, bratli commented on src/modules/InvitationForPunchOut/views/CreateIPO/CreateIPOHeader.tsx
> -    canBeCreated: boolean;
If you are using the same files for editing, change path from CreateIPO to something that can be used for creating and editing.

2020-12-18 10:35 UTC, bratli commented on src/modules/InvitationForPunchOut/views/CreateIPO/GeneralInfo/GeneralInfo.tsx
> +                text={selectedProject && selectedProject.description || generalInfo.projectName || 'Select'}
Project cannot be changed when editing. This should be disabled

2020-12-18 11:15 UTC, bratli requested changes

2020-12-18 13:29 UTC, bratli commented
When editing, the attachment step should always be completed. It doesnt make sense for the user to HAVE to stop by the attachment step if they are only updating description for example

2020-12-18 13:47 UTC, arildbjerkenes commented on src/modules/InvitationForPunchOut/views/CreateIPO/CreateIPOHeader.tsx
> -    canBeCreated: boolean;
Didn't dare to do this before merging...

2020-12-18 14:58 UTC, bratli requested changes

2020-12-18 14:58 UTC, bratli commented on src/modules/InvitationForPunchOut/views/CreateIPO/CreateIPO.tsx
> +    const saveUpdatedIpo = async (): Promise<void> => {
For some reason every time I update an IPO, the time is pushed up one hour. eg:
Meeting is from 11-12, then same IPO (just edit title) -> new time is 10-11
Repeat this, then new time is 9-10

2020-12-18 14:58 UTC, bratli commented on src/modules/InvitationForPunchOut/views/CreateIPO/CreateIPO.tsx
> +    useEffect(() => {
This fix may need to be done in Participants.tsx,
but if we have FR, and we have Additionally notify some people (the persons are on to or cc), then this needs to be mapped so that the user editing can see it and edit it. Let me know if you want me to show you

2020-12-21 15:34 UTC, arildbjerkenes commented on src/modules/InvitationForPunchOut/views/CreateIPO/CreateIPO.tsx
> +    const saveUpdatedIpo = async (): Promise<void> => {
Backend-issue

2020-12-22 10:44 UTC, bratli requested changes

2020-12-22 10:44 UTC, bratli commented on src/modules/InvitationForPunchOut/views/CreateAndEditIPO/Summary/Summary.tsx
> -                                <div style={{ fontSize: '12px'}}>{getNotifiedPersons(participant.role.persons, 'To')}</div>
When we are editing and see the summary, it looks like the snippet below feks. The "description" of the functional roles are replaced by just the word "description". Either have the actual description, or dont display it.

![image](https://user-images.githubusercontent.com/56581095/102878823-217be080-4449-11eb-824d-0d5e06862e84.png)

2020-12-22 10:44 UTC, bratli commented on src/modules/InvitationForPunchOut/views/CreateAndEditIPO/Participants/Participants.tsx
> +                                        {p.role ?
If the functional role has sendtopersonalemail='No', then the tooltip and text should not have the "To:.." property filled.
this is create:
![image](https://user-images.githubusercontent.com/56581095/102879667-73713600-444a-11eb-80b0-7b2f0061429a.png)
This is edit with the same FR:
![image](https://user-images.githubusercontent.com/56581095/102879707-8421ac00-444a-11eb-81a2-a6cc63e6e6e0.png)
(sorry for the bad quality).

In the summary view, the FR does not have To: to anyone, while when edit then we get:
![image](https://user-images.githubusercontent.com/56581095/102879787-aa474c00-444a-11eb-8b9f-c1838a9f208d.png)

I think this will become weird for functional roles where there are quite a few users.
And I also think you will have to do some mapping between the response from the invitation, and from webAPI when getting the functional roles. We do not store sendToPersonalEmail in the IPO database, but if you think we should then we can discuss it

2020-12-22 10:47 UTC, bratli commented
I also think we should check with @Cnordbo if it makes sense to combine create and edit like this, or to have two seperate folders - one for create and one for edit. It is very similar, but at the same time it is easier to make changes if they are seperate.

2020-12-22 12:56 UTC, Cnordbo commented on src/modules/InvitationForPunchOut/views/CreateAndEditIPO/CreateAndEditIPO.tsx
> +                setIsCreating(false);
This doesnt seem to belong here

2020-12-22 13:50 UTC, bratli commented
I am testing, and one one IPO, I have contractor (sortKey = 0), and constructioncompany (sortkey=1). When i save without making any changes, they both have sortkey = 1, which results in errors.

In this test I have person on contractor, and FR on construction company with usepersonalemail = yes

2020-12-22 14:11 UTC, bratli commented on src/modules/InvitationForPunchOut/views/CreateAndEditIPO/Participants/Participants.tsx
> +                            id: null,
can we make id and rowversion optional, and discard them from this file?

2021-01-04 10:54 UTC, arildbjerkenes commented on src/modules/InvitationForPunchOut/views/CreateAndEditIPO/Summary/Summary.tsx
> -                                <div style={{ fontSize: '12px'}}>{getNotifiedPersons(participant.role.persons, 'To')}</div>
fixed. Need to fetch available roles before populating data from existing invitation.

2021-01-04 11:11 UTC, arildbjerkenes commented on src/modules/InvitationForPunchOut/views/CreateAndEditIPO/Participants/Participants.tsx
> +                                        {p.role ?
By fetching available roles before invitation, i can find the role, and set parameter. Fetching roles seem to be a bit slow, by the way...

2021-01-04 11:22 UTC, arildbjerkenes commented on src/modules/InvitationForPunchOut/views/CreateAndEditIPO/Participants/Participants.tsx
> +                            id: null,
Yepp, we can :-)

2021-01-04 11:33 UTC, arildbjerkenes commented on src/modules/InvitationForPunchOut/views/CreateAndEditIPO/CreateAndEditIPO.tsx
> +                setIsCreating(false);
right

2021-01-04 12:01 UTC, arildbjerkenes commented
> I am testing, and one one IPO, I have contractor (sortKey = 0), and constructioncompany (sortkey=1). When i save without making any changes, they both have sortkey = 1, which results in errors.
> 
> In this test I have person on contractor, and FR on construction company with usepersonalemail = yes

I have now changed this so that when an invitation is created or updated, the sortKey will be set to the index it has in the array of participants. I suppose this should fix the issue.

2021-01-06 20:31 UTC, bratli requested changes

2021-01-06 20:31 UTC, bratli commented on src/modules/InvitationForPunchOut/views/ViewIPO/index.tsx
> +                        status={invitation.status}
I think you should instead of sending in status send:
editable/canEdit={invitation.status == IpoStatusEnum.PLANNED}
and then not do any logic on this inside the ViewIpoHeader component. Then the editable would be a bool on ProgressBarProps, and you can set disabled={!editable}

2021-01-06 20:31 UTC, bratli commented on src/modules/InvitationForPunchOut/views/ViewIPO/Attachments/index.tsx
> +        if (attachment.id && attachment.rowVersion) {
Just out of curiosity, did you notice a problem before checking for id and rowVersion?

2021-01-06 20:31 UTC, bratli commented on src/modules/InvitationForPunchOut/views/CreateAndEditIPO/EditIPO.tsx
> +                console.error('Upload attachment failed: ', error.message, error.data);
Should have error message that says upload or delete failed. Alternatively two seperate depending on what the error is

2021-01-06 20:31 UTC, bratli commented on src/modules/InvitationForPunchOut/views/CreateAndEditIPO/EditIPO.tsx
> +                            radioOption: person.required ? 'to' : 'cc'
When I am testing, and I create an IPO with a FR where I check "Additionally, notify individuals", and take an individual on "CC", I would expect "Additionally, notify individuals" to be checked and the person to be marked as "CC", when editing.

Let me know if you want me to show you.

2021-01-07 08:03 UTC, arildbjerkenes commented on src/modules/InvitationForPunchOut/views/CreateAndEditIPO/CreateAndEditIPOHeader.tsx
> +                <ButtonContainer>
Fixed

2021-01-07 09:52 UTC, arildbjerkenes commented on src/modules/InvitationForPunchOut/types.d.ts
> +/*export interface Attachment {
removed

2021-01-07 10:03 UTC, arildbjerkenes commented on src/modules/InvitationForPunchOut/views/ViewIPO/index.tsx
> +                        status={invitation.status}
done!

2021-01-07 10:06 UTC, arildbjerkenes commented on src/modules/InvitationForPunchOut/views/CreateAndEditIPO/EditIPO.tsx
> +                            radioOption: person.required ? 'to' : 'cc'
done

2021-01-07 10:07 UTC, arildbjerkenes commented on src/modules/InvitationForPunchOut/views/CreateAndEditIPO/EditIPO.tsx
> +                console.error('Upload attachment failed: ', error.message, error.data);
done

2021-01-07 14:51 UTC, bratli approved these changes

2021-01-08 06:56 UTC, merged