Unapprove button when an IPO is approved
equinor/procosys-js-frontend pull request #411
Opened 2021-01-14 12:12 UTC by arildbjerkenes

# Description

A button for un-approve of IPO is added. 

# Checklist:

- [ ] I have performed a self-review of my own code.
- [ ] I have linked my DevOps task using the AB# tag.
- [ ] My code is easy to read, and comments are added where needed.
- [ ] My code is covered by tests.

2021-01-18 21:51 UTC, bratli requested changes

2021-01-18 21:51 UTC, bratli commented on src/modules/InvitationForPunchOut/http/InvitationForPunchOutApiClient.ts
> +                    participants: unAcceptDetails.participants
there should not be a participants "attribute" here, only invitationRowVersion and participantRowVersion

2021-01-18 21:51 UTC, bratli commented on src/modules/InvitationForPunchOut/http/InvitationForPunchOutApiClient.ts
> +    async unAcceptPunchOut(id: number, unAcceptDetails: AcceptIPODto, setRequestCanceller?: RequestCanceler): Promise<PersonResponse[]> {
The response from endpoint will not be personResponse[], but just a string, the new invitationRowVersion

2021-01-18 21:51 UTC, bratli commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/index.tsx
> +    unAccept: (p: Participant, e: AttNoteData[]) => Promise<any>;
The person unaccepting/approving will not send any info on the participants in this endpoint

2021-01-18 21:51 UTC, bratli commented on src/modules/InvitationForPunchOut/views/ViewIPO/index.tsx
> +            participants: attNoteData
again, remove participants here

2021-01-18 21:51 UTC, bratli commented on src/modules/InvitationForPunchOut/views/ViewIPO/index.tsx
> +        const acceptDetails: AcceptIPODto = {
1. rename to unacceptDetails

2. Need a new Dto, UnacceptIpoDto

2021-01-18 21:51 UTC, bratli commented on src/modules/InvitationForPunchOut/views/ViewIPO/index.tsx
> +        await apiClient.acceptPunchOut(params.ipoId, acceptDetails);
apiClient.unacceptPunchOut, not accept. Copy/paste?

2021-01-18 21:51 UTC, bratli commented on src/modules/InvitationForPunchOut/http/InvitationForPunchOutApiClient.ts
> +    async unAcceptPunchOut(id: number, unAcceptDetails: AcceptIPODto, setRequestCanceller?: RequestCanceler): Promise<PersonResponse[]> {
Replace AcceptIPODto with UnacceptIpoDto

2021-01-18 21:51 UTC, bratli commented
@arildbjerkenes Endpoint is ready :)

2021-01-18 22:26 UTC, bratli commented on src/modules/InvitationForPunchOut/http/InvitationForPunchOutApiClient.ts
> +    async unAcceptPunchOut(id: number, unAcceptDetails: AcceptIPODto, setRequestCanceller?: RequestCanceler): Promise<PersonResponse[]> {
I dint hink you use the response, because you do getInvitation right after unaccepting

2021-01-19 08:28 UTC, arildbjerkenes commented on src/modules/InvitationForPunchOut/http/InvitationForPunchOutApiClient.ts
> +                    participants: unAcceptDetails.participants
fixed

2021-01-19 08:29 UTC, arildbjerkenes commented on src/modules/InvitationForPunchOut/http/InvitationForPunchOutApiClient.ts
> +    async unAcceptPunchOut(id: number, unAcceptDetails: AcceptIPODto, setRequestCanceller?: RequestCanceler): Promise<PersonResponse[]> {
fixed

2021-01-20 08:48 UTC, bratli commented
lots of errors in console when clicking compelte/approve buttons

![image](https://user-images.githubusercontent.com/56581095/105150161-b2a3ad00-5b04-11eb-9888-9fb4e31487ca.png)

2021-01-20 08:54 UTC, bratli commented
When following this workflow:
I am contractor and construction company.
I complete the IPO (should be able to update while ipo is in completed stage). The Update button is active. But when I refresh page, the Update button becomes disabled... Need to fix this.

2021-01-20 08:55 UTC, bratli requested changes
see comments

2021-01-20 08:56 UTC, bratli commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/ParticipantsTable/index.tsx
> +const tooltipUnApprove = <div>Punch round has been approved.</div>;
This tooltips has the same "style" as the others, but I think it is a bit weird to have this tooltip here, because maybe they approved by mistake, so it is not actually apptoved. Maybe change to just "Unapprove the punch round"? Or ask Jon

2021-01-24 18:02 UTC, merged