Feature 80735: UI - Table of IPOs
equinor/procosys-js-frontend pull request #442
Opened 2021-02-03 09:13 UTC by janhagevold

# Description

- Add material-table from Preservation design

Completes: AB#80735

# Checklist:

- [ ] I have performed a self-review of my own code.
- [ ] I have linked my DevOps task using the AB# tag.
- [ ] My code is easy to read, and comments are added where needed.
- [ ] My code is covered by tests.

2021-02-04 14:12 UTC, bratli requested changes

2021-02-04 14:12 UTC, bratli commented on src/modules/InvitationForPunchOut/http/InvitationForPunchOutApiClient.ts
> +    commPkgs?: Pick<CommPkgResponse, 'commPkgNo'>[];
just fyi, when the endpoint is ready I am just returing a list of strings for commPkgNos and mcPkgNos, as we dont need as much detail in this endpoint

2021-02-04 14:12 UTC, bratli commented on src/modules/InvitationForPunchOut/http/InvitationForPunchOutApiClient.ts
> +        return await new Promise<IPOsResponse>(resolve => setTimeout(() => resolve(
Same here, when endpoint is ready you will see some different naming of attributes than this, becuase I have tried to follow the same stle as for the rest of IPO. Eg. Completed is CompeltedAtUtc

2021-02-04 14:12 UTC, bratli commented on src/modules/Header/index.tsx
> +                            { (ProCoSysSettings.featureIsEnabled('IPO')) &&
Dont merge this part in before everything is ready. This is so that users in QP/prod wont find it and think that is is ready. For now we can just type the url when testing

2021-02-04 14:12 UTC, bratli commented on src/modules/Header/index.tsx
> +                            { (ProCoSysSettings.featureIsEnabled('IPO')) &&
Also, is it possible to make it a little bit longer? The scrollbar is jjust scrolling some millimeters, so I would rather not have it 
![image](https://user-images.githubusercontent.com/56581095/106903913-dec14f80-66fa-11eb-850a-5f0b42ff3c09.png)

2021-02-04 14:12 UTC, bratli commented on src/modules/InvitationForPunchOut/views/SearchIPO/Table/index.tsx
> +import { CommPkg, IPO, McPkg } from '../types';
I think it is important that we follow the same design on tables. This table is "cleaner" than the ones in preservation feks, or the ones in IPO when searching for scope (not as many horizaontal lines). If you think this design is better, talk to Jon to see if he agrees, and then create a PBI to make all tables in this design. It is important that we follow the same design, if not the next developer will add his preferences, and we will end up with a ton of different designs. 
To summarize, either make this table follow the design of other tables, or create a PBI to change other tables in new solution to follow this design

2021-02-05 06:22 UTC, janhagevold commented on src/modules/Header/index.tsx
> +                            { (ProCoSysSettings.featureIsEnabled('IPO')) &&
The height depends on the view height with default 80vh. We can definitely bump this up a bit if your screen is a standard that we would see often.

2021-02-05 06:26 UTC, janhagevold commented on src/modules/InvitationForPunchOut/views/SearchIPO/Table/index.tsx
> +import { CommPkg, IPO, McPkg } from '../types';
I had added a line of css to remove the very bottom border as it looked cleaner. Didn't notice that it affected all the rows. Reverting this for now so it corresponds with existing tables.

2021-02-05 10:00 UTC, arildbjerkenes approved these changes

2021-02-05 10:06 UTC, merged