Feature 80737:   UI - IPO search filter
equinor/procosys-js-frontend pull request #444
Opened 2021-02-09 09:12 UTC by janhagevold

# Description

- Add filters for IPO search

Completes: AB#80737

# Checklist:

- [ ] I have performed a self-review of my own code.
- [ ] I have linked my DevOps task using the AB# tag.
- [ ] My code is easy to read, and comments are added where needed.
- [ ] My code is covered by tests.

2021-02-11 12:44 UTC, Cnordbo commented on src/modules/Header/index.tsx
> +                            }
This is possibly just missing a merge. 

But this should also be setup as a <NavLink> item (look at the `moduleTabs.tsx`), otherwise it will re-navigate to the solution instead of using SPA routing.

2021-02-11 13:09 UTC, Cnordbo requested changes

2021-02-11 13:09 UTC, Cnordbo commented on src/modules/InvitationForPunchOut/views/SearchIPO/index.tsx
> +                    .then((roles: any) => {
Avoid using `any` where type is known. 

No need for `.then`

2021-02-12 14:48 UTC, Cnordbo approved these changes

2021-02-12 14:48 UTC, Cnordbo commented on src/modules/Header/index.tsx
> +import { Link, NavLink, useParams } from 'react-router-dom';
NavLink is unused

2021-02-12 14:56 UTC, Cnordbo requested changes
This will decrade our overall coverage report by alot. Please test your code. 

![image](https://user-images.githubusercontent.com/385693/107783588-bc5ab200-6d4a-11eb-9de7-c32ee6254b94.png)

2021-02-12 14:58 UTC, Cnordbo commented on src/modules/InvitationForPunchOut/views/SearchIPO/index.tsx
> +import { FunctionalRole } from '../ViewIPO/types';
Unused import

2021-02-15 09:46 UTC, bratli approved these changes

2021-02-15 10:29 UTC, merged