Feature 80941: UI - Add application insights custom events
equinor/procosys-js-frontend pull request #451
Opened 2021-02-11 12:16 UTC by janhagevold

# Description

- Add custom events for created, edited, completed, accepted, signed, canceled

Completes: AB#80941

# Checklist:

- [ ] I have performed a self-review of my own code.
- [ ] I have linked my DevOps task using the AB# tag.
- [ ] My code is easy to read, and comments are added where needed.
- [ ] My code is covered by tests.

2021-02-11 12:29 UTC, Cnordbo requested changes
Fix the `plant` vs `plant.title` comment. Everything else looks fine. 

Take into consideration the universal plant setup in analytics if you wish. or else we should create a tech story on this.

2021-02-11 12:29 UTC, Cnordbo commented on src/modules/InvitationForPunchOut/views/CreateAndEditIPO/CreateIPO.tsx
> +                analystics.trackUserAction(IpoCustomEvents.CREATED, { plant: plant.title, project: generalInfo.projectName, type: generalInfo.poType.value });
Just to close a  tech story (not yet created) at the same time here. 

We should extend the Analytics context with a function for setting the plant, and then change that plant from the plantcontext everytime current plant changes. 

plantContext already uses analytics, so it should be a simple win, with a potentially huge gain for us. And you would avoid sending in the plant for every event you want to track. 

As Project and other parameters arent default or required by every module, this still needs to be sent in as you do here. 

This will help us setup so that all events potentially has a plant (if specified)

Simply a request, but doing this later requires a small refactor of your code here.

2021-02-11 12:29 UTC, Cnordbo commented on src/modules/InvitationForPunchOut/views/CreateAndEditIPO/EditIPO.tsx
> +                analystics.trackUserAction(IpoCustomEvents.EDITED, { plant: plant, project: generalInfo.projectName, type: generalInfo.poType.value });
this is sending in the entire plant object, where as other places your using `plant.title`

2021-02-11 13:14 UTC, Cnordbo commented on src/core/PlantContext.tsx
> +        analytics.setCurrentPlant(currentPlant.title);
Should we use the ID here? It might be easier to track across projects then. (PCS$JOHAN_SVERDRUP)

2021-02-11 13:16 UTC, janhagevold commented on src/core/PlantContext.tsx
> +        analytics.setCurrentPlant(currentPlant.title);
changed to plantInPath

2021-02-11 13:22 UTC, Cnordbo approved these changes
Address that last issue, and we should be good to go. 

LGTM.

2021-02-11 13:22 UTC, Cnordbo commented on src/core/PlantContext.tsx
> +        analytics.setCurrentPlant(plantInPath);
this should react to 
```js
useEffect(() => { 
  analytics.setCurrentPlant(currentPlant.id);
}, [currentPlant])
```

2021-02-12 09:30 UTC, Cnordbo approved these changes

2021-02-12 12:42 UTC, janhagevold commented on src/core/PlantContext.tsx
> +        analytics.setCurrentPlant(plantInPath);
With dependency on currentPlant, the analytics instance gets plant on first page load. When changing plant, _plant on the instance is set to empty string (constructor is executed again?).
_plant is updated properly as intended when moved analytics.setCurrentPlant() to PlantContext's own setCurrentPlant function as in latest commit.

2021-02-12 14:42 UTC, Cnordbo approved these changes

2021-02-15 05:37 UTC, merged