Feature 80535: UI - remove outlook flyout and add popover
equinor/procosys-js-frontend pull request #453
Opened 2021-02-16 08:19 UTC by VRiveland

# Description

Removed outlook flyover and added a popover instead.

Completes: AB#80535

# Checklist:

- [x] I have performed a self-review of my own code.
- [x] I have linked my DevOps task using the AB# tag.
- [x] My code is easy to read, and comments are added where needed.
- [x] My code is covered by tests.

2021-02-16 11:05 UTC, bratli requested changes
Requested some refactoring of code to match existing code that is similar. If you disagree we can discuss it (I am not a front end expert)

2021-02-16 11:05 UTC, bratli commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/ParticipantsTable/CustomPopover/index.tsx
> +    const openPopover = (event: React.SyntheticEvent): void =>{
2. remove

2021-02-16 11:05 UTC, bratli commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/ParticipantsTable/CustomPopover/index.tsx
> +    const closePopover = ():void => {
3. add a state variable to component
const [isActive, setIsActive] = useState(false);

Rename to togglePopover, and do: setIsActive(!isActive);

2021-02-16 11:05 UTC, bratli commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/ParticipantsTable/CustomPopover/index.tsx
> +        <FloatingPopover onClose={ closePopover } open={activePopover === `popover${participant.functionalRole.id.toString()}`} placement="right">
onClose={togglePopover} and open={isActive}

2021-02-16 11:05 UTC, bratli commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/ParticipantsTable/CustomPopover/index.tsx
> +            <PopoverAnchor id={ participant.sortKey.toString() + 'test' }>
do we need ids or these "subcomponents"? Don't think its anything wrong with it, but we dont do it in similar places unless needed

2021-02-16 11:05 UTC, bratli commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/ParticipantsTable/CustomPopover/index.tsx
> +                    onClick={ openPopover }
onClick={togglePopover}

2021-02-16 11:34 UTC, VRiveland commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/ParticipantsTable/CustomPopover/index.tsx
> +interface CustomPopoverProps {
This was the way it was done in the storybook, as that way you ensure that only one of the popovers can be open at the same time. I could change this, but then the component would work differently than the component does on the Equinor storybook site.

2021-02-16 11:49 UTC, VRiveland commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/ParticipantsTable/CustomPopover/index.tsx
> +            <PopoverAnchor id={ participant.sortKey.toString() + 'test' }>
The Ids are only for testing purposes. The subcomponents of the <FloatingPopover> are the different "subcomponents" that the popover component needs except for <CustomTable> and every "subcomponent" inside of the <CustomTable>. Those are styled <div>s from the style file. I could add the styling inline if that would be better.

2021-02-16 12:18 UTC, VRiveland commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/ParticipantsTable/CustomPopover/index.tsx
> +interface CustomPopoverProps {
Never mind, took a look at your other comments and saw what you meant. Will fix.

2021-02-16 12:40 UTC, bratli commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/ParticipantsTable/index.tsx
> +    const handlePopoverChange = (newValue: string): void =>{
You can remove this I think

2021-02-16 12:41 UTC, janhagevold commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/ParticipantsTable/index.tsx
> +    const [popoverActive, setPopoverActive] = useState<string>('');
this can now be removed

2021-02-16 12:43 UTC, janhagevold commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/ParticipantsTable/index.tsx
> +    const handlePopoverChange = (newValue: string): void =>{
handlePopoverChange is not used anylonger

2021-02-16 14:09 UTC, VRiveland commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/ParticipantsTable/CustomPopover/index.tsx
> +            <PopoverAnchor id={ participant.sortKey.toString() + 'test' }>
The only other place I'm able to find a popover in the code is for saved filters in preservation. There the material-ui popover is used, not the Equinor one. The story in Equinor storybook uses these "subcomponents". If they aren't needed and we're "allowed" to use the Equinor components differently than they do in the story, then I can change this implementation to more closely resemble the one in saved filters.

2021-02-16 15:25 UTC, bratli commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/ParticipantsTable/CustomPopover/index.tsx
> +            <PopoverAnchor id={ participant.sortKey.toString() + 'test' }>
Sorry, it was a typo on my part, I see the confusion. Was supposed to say do we need ids ON these subcomponents

2021-02-16 15:42 UTC, bratli commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/ParticipantsTable/__tests__/ParticipantsTable.test.jsx
> +                if(participant.functionalRole !== null){
combine these if's (same with test below)

2021-02-16 15:45 UTC, bratli commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/ParticipantsTable/CustomPopover/index.tsx
> +            <PopoverTitle id={ participant.sortKey.toString() + 'title' } >
this id is not used, so it can be removed

2021-02-16 15:53 UTC, bratli commented on src/modules/InvitationForPunchOut/views/ViewIPO/GeneralInfo/ParticipantsTable/CustomPopover/index.tsx
> +    const togglePopover = (event: React.SyntheticEvent): void =>{
remove arguments from toggle popover, event is not used, just have ()

2021-02-17 07:14 UTC, janhagevold approved these changes

2021-02-17 07:52 UTC, bratli approved these changes

2021-02-17 07:53 UTC, merged