Feature/80840 UI save filter functionality
equinor/procosys-js-frontend pull request #457
Opened 2021-02-23 08:26 UTC by VRiveland

# Description

Added saved filter functionality to front end.

Completes: AB#80840

# Checklist:

- [x] I have performed a self-review of my own code.
- [x] I have linked my DevOps task using the AB# tag.
- [x] My code is easy to read, and comments are added where needed.
- [ ] My code is covered by tests.

2021-03-02 09:23 UTC, bratli commented on src/modules/InvitationForPunchOut/views/SearchIPO/index.tsx
>  import { Container, ContentContainer, DropdownItem, FilterContainer, Header, HeaderContainer, StyledButton, TooltipText } from './index.style';
Do you get this as well?

2021-03-02 09:33 UTC, bratli commented on src/modules/InvitationForPunchOut/views/SearchIPO/Filter/SavedFilters/index.tsx
> +            showSnackbarNotification('Filter is no longer default.', 5000);
I guess the message should be, "Filter is set to default" or something if we are setting a filter to default

2021-03-02 09:34 UTC, bratli requested changes
See comments

2021-03-02 09:39 UTC, VRiveland commented on src/modules/InvitationForPunchOut/views/SearchIPO/index.tsx
>  import { Container, ContentContainer, DropdownItem, FilterContainer, Header, HeaderContainer, StyledButton, TooltipText } from './index.style';
Checked now. I only get it when I pick a project with at least one IPO.

2021-03-02 09:47 UTC, bratli commented on src/modules/InvitationForPunchOut/views/SearchIPO/index.tsx
>  import { Container, ContentContainer, DropdownItem, FilterContainer, Header, HeaderContainer, StyledButton, TooltipText } from './index.style';
Okay, can you check it out?

2021-03-02 09:55 UTC, VRiveland commented on src/modules/InvitationForPunchOut/views/SearchIPO/index.tsx
>  import { Container, ContentContainer, DropdownItem, FilterContainer, Header, HeaderContainer, StyledButton, TooltipText } from './index.style';
Yes, I'll look into it

2021-03-02 10:17 UTC, VRiveland commented on src/modules/InvitationForPunchOut/views/SearchIPO/index.tsx
>  import { Container, ContentContainer, DropdownItem, FilterContainer, Header, HeaderContainer, StyledButton, TooltipText } from './index.style';
The only place where <a> is a child of another <a> is in the table of IPOs, where I haven't changed anything. I get the same warning when I run the version of the code without the changes in this PR. It comes from when the table is generated, specifically the IPO ID links. This might be fixed once the table component has been changed.

2021-03-03 10:33 UTC, bratli approved these changes

2021-03-03 10:36 UTC, merged