Feature/81123 UI switch material table
equinor/procosys-js-frontend pull request #475
Opened 2021-03-08 10:38 UTC by chormaz

# Description

New table component based on react-table. Used p.t. in Preservation module.

Please include a summary of the change and which issue is fixed. 

Dependencies: 
"react-table": "^7.6.3",
"react-virtualized-auto-sizer": "^1.0.4",
"react-window": "^1.8.6",
"classnames": "^2.2.6",
"@types/react-table": "^7.0.28",
"@types/react-virtualized-auto-sizer": "^1.0.0",
"@types/react-window": "^1.8.2",

Completes: AB#81123

# Checklist:

- [ x] I have performed a self-review of my own code.
- [ x] I have linked my DevOps task using the AB# tag.
- [ x] My code is easy to read, and comments are added where needed.
- [ x] My code is covered by tests.

2021-03-09 14:50 UTC, Cnordbo commented
Just some initial findings: 

* We try to avoid using "any" as a type where the type is known. 
* Are there any solutions to giving the mapped values a key instead of overriding the eslint rule? 
* The general styling in the solution uses Custom components and uses props as their modifiers. This should be the main way of styling anything in the app. Could you have a look at your styles to see if this can fit your usages as well?

2021-03-23 09:11 UTC, Cnordbo requested changes
There is currently 32 failing tests that needs to be addressed.

2021-03-25 08:10 UTC, chormaz commented
@janhagevold I'm not sure I successfully merged your changes from #480 regarding select scope in CreateEdit IPO. Could you verify that it still works as expected?

2021-03-26 06:09 UTC, janhagevold commented
> @janhagevold I'm not sure I successfully merged your changes from #480 regarding select scope in CreateEdit IPO. Could you verify that it still works as expected?

Can not verify for MDP as checkboxes are missing in table. DP seems to work as expected.

2021-03-26 10:12 UTC, Cnordbo submitted a review, later dismissed

2021-04-06 06:03 UTC, chormaz commented on src/components/Table/__tests__/table.test.jsx
> +const tags = {
Implemented own file

2021-04-06 06:04 UTC, chormaz commented on src/components/Table/ProcosysTable.tsx
> +import AutoSizer from 'react-virtualized-auto-sizer';
The reason for using this is the virtualization.

2021-04-09 07:06 UTC, janhagevold requested changes

2021-04-09 07:06 UTC, janhagevold commented on src/modules/InvitationForPunchOut/views/CreateAndEditIPO/SelectScope/CommPkgTable.tsx
> +    const hasValidSystem2 = (chosenSystem: string, system: string): boolean => {
looks unused

2021-04-09 07:06 UTC, janhagevold commented on src/modules/InvitationForPunchOut/views/CreateAndEditIPO/SelectScope/Table.style.ts
> +        bottom: 12px;
bottom: 6px?

2021-04-09 07:13 UTC, chormaz commented on src/modules/InvitationForPunchOut/views/CreateAndEditIPO/SelectScope/CommPkgTable.tsx
> +    const hasValidSystem2 = (chosenSystem: string, system: string): boolean => {
Removed

2021-04-09 07:59 UTC, chormaz commented on src/components/AttachmentList/index.tsx
> +        const attachment = row.value as Attachment;
Because the value property of row is any.

2021-04-09 08:18 UTC, chormaz commented on src/components/AttachmentList/index.tsx
> +            <div style={{ height: '40vh' }}>
Replaced with styled component TableContainer.

2021-04-09 08:20 UTC, chormaz commented on src/components/AttachmentList/index.tsx
> -                style={{ boxShadow: 'none' }}
This is in the old version

2021-04-09 08:48 UTC, chormaz commented on src/components/Table/filters.tsx
> +                style={{ width: 'calc(100% - 14px)' }}
Done

2021-04-09 08:53 UTC, chormaz commented on src/modules/InvitationForPunchOut/views/CreateAndEditIPO/SelectScope/CommPkgTable.tsx
> +            <div style={{ height: '50vh' }}>
Done

2021-04-09 08:57 UTC, chormaz commented on src/modules/Preservation/views/ScopeOverview/TransferDialog.tsx
> +            <div style={{ height: '50%' }}>
Done

2021-04-09 08:59 UTC, chormaz commented on src/modules/Preservation/views/ScopeOverview/VoidDialog.tsx
> +        <div style={{ height: '65vh' }}>
Done

2021-04-09 08:59 UTC, chormaz commented on src/modules/Preservation/views/ScopeOverview/VoidDialog.tsx
> +                <div style={{ height: '35vh' }}>
Done

2021-04-09 08:59 UTC, chormaz commented on src/modules/Preservation/views/ScopeOverview/VoidDialog.tsx
> +                <div style={{ height: '35vh' }}>
Done

2021-04-12 07:01 UTC, ErlendLygre approved these changes

2021-04-12 07:25 UTC, janhagevold approved these changes

2021-04-12 07:30 UTC, merged