Feature/92506 Should be able to add scope across systems
equinor/procosys-js-frontend pull request #647
Opened 2022-07-28 13:44 UTC by Prestholm

# Description

Should be able to add scope across systems. This means do not disable scope that is not on the same system as selected scope

Completes: AB#92506

# Checklist:

- [X] I have performed a self-review of my own code.
- [X] I have linked my DevOps task using the AB# tag.
- [X] My code is easy to read, and comments are added where needed.
- [ ] My code is covered by tests.

2022-07-29 12:26 UTC, bratli commented on src/modules/InvitationForPunchOut/views/CreateAndEditIPO/SelectScope/CommPkgTable.tsx
> +            (systemString: string) => {
Does this prevent being able to add scope accross sections? The system-attribute looks like this: "system|subsystem" for most plants, but for Heimdal it looks like this "section|system|subsystem".

2022-08-31 07:14 UTC, bratli requested changes

2022-08-31 07:14 UTC, bratli commented on src/modules/InvitationForPunchOut/views/CreateAndEditIPO/SelectScope/CommPkgTable.tsx
> +                if (!filter.trim()) {
Isn't this somehting that was removed in another PR?

2022-09-16 08:50 UTC, Prestholm commented on src/modules/InvitationForPunchOut/views/CreateAndEditIPO/SelectScope/CommPkgTable.tsx
> +                if (!filter.trim()) {
Correct, removed now!

2022-09-22 07:27 UTC, VRiveland commented on src/modules/InvitationForPunchOut/views/CreateAndEditIPO/SelectScope/CommPkgTable.tsx
> +                                let y = true;
Needs better variable names

2022-09-22 07:31 UTC, VRiveland reviewed
I'll fix

2022-09-22 08:09 UTC, merged