Bug/94283 Selected scope is removed when making a new search
equinor/procosys-js-frontend pull request #651
Opened 2022-08-17 10:42 UTC by Prestholm

# Description

Please include a summary of the change and which issue is fixed. 
List any external dependencies that are required for this change.

Completes: AB#94283

# Checklist:

- [ ] I have performed a self-review of my own code.
- [ ] I have linked my DevOps task using the AB# tag.
- [ ] My code is easy to read, and comments are added where needed.
- [ ] My code is covered by tests.

2022-08-18 08:01 UTC, VRiveland approved these changes

2022-08-18 08:50 UTC, bratli commented on src/modules/InvitationForPunchOut/views/CreateAndEditIPO/SelectScope/CommPkgTable.tsx
> -            removeAllSelectedCommPkgsInScope();
I am having trouble getting frontend locally, but have you tested than unselecting packages works as expected?

2022-08-18 08:55 UTC, VRiveland commented on src/modules/InvitationForPunchOut/views/CreateAndEditIPO/SelectScope/CommPkgTable.tsx
> -            removeAllSelectedCommPkgsInScope();
Woah, I hadn't tested that properly at least. Unselecting all doesn't work.

2022-08-18 09:59 UTC, bratli requested changes

2022-08-18 09:59 UTC, bratli commented on src/modules/InvitationForPunchOut/views/CreateAndEditIPO/SelectScope/CommPkgTable.tsx
> -            removeAllSelectedCommPkgsInScope();
:(

2022-08-18 09:59 UTC, bratli requested changes

2022-08-18 09:59 UTC, bratli commented on src/modules/InvitationForPunchOut/views/CreateAndEditIPO/SelectScope/CommPkgTable.tsx
> -            removeAllSelectedCommPkgsInScope();
Need to fix this

2022-08-19 07:09 UTC, Prestholm commented on src/modules/InvitationForPunchOut/views/CreateAndEditIPO/SelectScope/CommPkgTable.tsx
> -            removeAllSelectedCommPkgsInScope();
Nice catch!

2022-08-19 10:24 UTC, bratli approved these changes
Don't unserstand why this works, but seems fine when testing

🥇

2022-08-22 10:01 UTC, VRiveland approved these changes

2022-08-22 12:13 UTC, merged